version: '3.9'
services:
  app:
    container_name: myapp
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - pg_db
    networks:
      - my_nat

  pg_db:
    image: postgres:latest
    container_name: mydb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data 777
    networks:
      - my_nat

volumes:
  data:

networks:
  my_nat:
    driver: bridge