version: '3.9'
services:
  app:
    container_name: myapp
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - "8000:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - my_nat

  postgres:
    image: postgres:latest
    container_name: my_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - my_nat

volumes:
  data:

networks:
  my_nat:
    driver: bridge